<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Client extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Client_model');
    } 

    /*
     * Listing of clients
     */
    function index()
    {
        $params['limit'] = RECORDS_PER_PAGE; 
        $params['offset'] = ($this->input->get('per_page')) ? $this->input->get('per_page') : 0;
        
        $config = $this->config->item('pagination');
        $config['base_url'] = site_url('client/index?');
        $config['total_rows'] = $this->Client_model->get_all_clients_count();
        $this->pagination->initialize($config);

        $data['clients'] = $this->Client_model->get_all_clients($params);
        
        $data['_view'] = 'client/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new client
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('ClientAddress','ClientAddress','required|min_length[5]');
		$this->form_validation->set_rules('ClientName','ClientName','min_length[3]|required');
		$this->form_validation->set_rules('ClientPhone','ClientPhone','min_length[5]|required');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'ClientName' => $this->input->post('ClientName'),
				'ClientAddress' => $this->input->post('ClientAddress'),
				'ClientPhone' => $this->input->post('ClientPhone'),
            );
            
            $client_id = $this->Client_model->add_client($params);
            redirect('client/index');
        }
        else
        {            
            $data['_view'] = 'client/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a client
     */
    function edit($ClientId)
    {   
        // check if the client exists before trying to edit it
        $data['client'] = $this->Client_model->get_client($ClientId);
        
        if(isset($data['client']['ClientId']))
        {
            $this->load->library('form_validation');

			$this->form_validation->set_rules('ClientAddress','ClientAddress','required|min_length[5]');
			$this->form_validation->set_rules('ClientName','ClientName','min_length[3]|required');
			$this->form_validation->set_rules('ClientPhone','ClientPhone','min_length[5]|required');
		
			if($this->form_validation->run())     
            {   
                $params = array(
					'ClientName' => $this->input->post('ClientName'),
					'ClientAddress' => $this->input->post('ClientAddress'),
					'ClientPhone' => $this->input->post('ClientPhone'),
                );

                $this->Client_model->update_client($ClientId,$params);            
                redirect('client/index');
            }
            else
            {
                $data['_view'] = 'client/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The client you are trying to edit does not exist.');
    } 

    /*
     * Deleting client
     */
    function remove($ClientId)
    {
        $client = $this->Client_model->get_client($ClientId);

        // check if the client exists before trying to delete it
        if(isset($client['ClientId']))
        {
            $this->Client_model->delete_client($ClientId);
            redirect('client/index');
        }
        else
            show_error('The client you are trying to delete does not exist.');
    }
    
}
