<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Order extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Order_model');
    } 

    /*
     * Listing of orders
     */
    function index()
    {
        $data['orders'] = $this->Order_model->get_all_orders();
        
        $data['_view'] = 'order/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new order
     */
    function add()
    {   
        $this->load->library('form_validation');

		$this->form_validation->set_rules('ItemQuantity','ItemQuantity','required|greater_than[0]');
		
		if($this->form_validation->run())     
        {   
            $params = array(
				'ClientId' => $this->input->post('ClientId'),
				'ItemId' => $this->input->post('ItemId'),
				'ItemQuantity' => $this->input->post('ItemQuantity'),
            );
            
            $order_id = $this->Order_model->add_order($params);
            redirect('order/index');
        }
        else
        {
			$this->load->model('Client_model');
			$data['all_clients'] = $this->Client_model->get_all_clients();

			$this->load->model('Item_model');
			$data['all_items'] = $this->Item_model->get_all_items();
            
            $data['_view'] = 'order/add';
            $this->load->view('layouts/main',$data);
        }
    } 

    /*
     * Deleting order
     */
    function remove($OrderId)
    {
        $order = $this->Order_model->get_order($OrderId);

        // check if the order exists before trying to delete it
        if(isset($order['OrderId']))
        {
            $this->Order_model->delete_order($OrderId);
            redirect('order/index');
        }
        else
            show_error('The order you are trying to delete does not exist.');
    }
    
}
