<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Client_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get client by ClientId
     */
    function get_client($ClientId)
    {
        return $this->db->get_where('Clients',array('ClientId'=>$ClientId))->row_array();
    }
    
    /*
     * Get all clients count
     */
    function get_all_clients_count()
    {
        $this->db->from('Clients');
        return $this->db->count_all_results();
    }
        
    /*
     * Get all clients
     */
    function get_all_clients($params = array())
    {
        $this->db->order_by('ClientId', 'desc');
        if(isset($params) && !empty($params))
        {
            $this->db->limit($params['limit'], $params['offset']);
        }
        return $this->db->get('Clients')->result_array();
    }
        
    /*
     * function to add new client
     */
    function add_client($params)
    {
        $this->db->insert('Clients',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update client
     */
    function update_client($ClientId,$params)
    {
        $this->db->where('ClientId',$ClientId);
        return $this->db->update('Clients',$params);
    }
    
    /*
     * function to delete client
     */
    function delete_client($ClientId)
    {
        return $this->db->delete('Clients',array('ClientId'=>$ClientId));
    }
}
