<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Item_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get item by ItemId
     */
    function get_item($ItemId)
    {
        return $this->db->get_where('Items',array('ItemId'=>$ItemId))->row_array();
    }
        
    /*
     * Get all items
     */
    function get_all_items()
    {
        $this->db->order_by('ItemId', 'desc');
        return $this->db->get('Items')->result_array();
    }
        
    /*
     * function to add new item
     */
    function add_item($params)
    {
        $this->db->insert('Items',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update item
     */
    function update_item($ItemId,$params)
    {
        $this->db->where('ItemId',$ItemId);
        return $this->db->update('Items',$params);
    }
    
    /*
     * function to delete item
     */
    function delete_item($ItemId)
    {
        return $this->db->delete('Items',array('ItemId'=>$ItemId));
    }
}
