<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Supplyer_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get supplyer by SupplyerId
     */
    function get_supplyer($SupplyerId)
    {
        return $this->db->get_where('Supplyers',array('SupplyerId'=>$SupplyerId))->row_array();
    }
        
    /*
     * Get all supplyers
     */
    function get_all_supplyers()
    {
        $this->db->order_by('SupplyerId', 'desc');
        return $this->db->get('Supplyers')->result_array();
    }
        
    /*
     * function to add new supplyer
     */
    function add_supplyer($params)
    {
        $this->db->insert('Supplyers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update supplyer
     */
    function update_supplyer($SupplyerId,$params)
    {
        $this->db->where('SupplyerId',$SupplyerId);
        return $this->db->update('Supplyers',$params);
    }
    
    /*
     * function to delete supplyer
     */
    function delete_supplyer($SupplyerId)
    {
        return $this->db->delete('Supplyers',array('SupplyerId'=>$SupplyerId));
    }
}
